import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: Center(
          child: Frame1(),
        ),
      ),
    );
  }
}

class Frame1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 1920,
      height: 1080,
      clipBehavior: Clip.antiAlias,
      decoration: BoxDecoration(color: Color(0xFFD77137)),
      child: Stack(
        children: [
          Positioned(
            left: 0,
            top: 61,
            child: Container(
              width: 711,
              height: 710,
              decoration: ShapeDecoration(
                color: Color(0xFFC66A34),
                shape: OvalBorder(
                  side: BorderSide(width: 5, color: Colors.white),
                ),
              ),
            ),
          ),
          Positioned(
            left: 1127,
            top: 590,
            child: Container(
              width: 710,
              height: 711,
              decoration: ShapeDecoration(
                color: Color(0xFFC66A34),
                shape: OvalBorder(
                  side: BorderSide(width: 5, color: Colors.white),
                ),
              ),
            ),
          ),
          Positioned(
            left: 125,
            top: 870,
            child: Container(
              width: 711,
              height: 710,
              decoration: ShapeDecoration(
                color: Color(0xFFC66A34),
                shape: OvalBorder(
                  side: BorderSide(width: 5, color: Colors.white),
                ),
              ),
            ),
          ),
          Positioned(
            left: 1305,
            top: -220,
            child: Container(
              width: 711,
              height: 711,
              decoration: ShapeDecoration(
                color: Color(0xFFC76A34),
                shape: OvalBorder(
                  side: BorderSide(width: 5, color: Colors.white),
                ),
              ),
            ),
          ),
          Center(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  'Natural Language Processing',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 55,
                    fontFamily: 'McLaren',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
                SizedBox(height: 20),
                Text(
                  'SMART\nCalculator',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 107,
                    fontFamily: 'McLaren',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
                SizedBox(height: 20),
                ElevatedButton(
                  onPressed: () {
                    // Add your onPressed code here!
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Color(0xFFC76A34),
                    disabledBackgroundColor: Colors.white,
                    side: BorderSide(width: 5, color: Colors.white),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                    fixedSize: const Size(350, 151),
                  ),
                  child: Center(
                    child: Text(
                      'Start',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 80,
                        fontFamily: 'McLaren',
                        fontWeight: FontWeight.w400,
                        height: 0,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}